# Generated by Django 3.0.7 on 2020-06-26 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trimester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_1', models.IntegerField(blank=True, null=True)),
                ('grade_2', models.IntegerField(blank=True, null=True)),
                ('average', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentYear',
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Year'),
        ),
    ]
