# Generated by Django 3.0.7 on 2020-06-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200626_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimester',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
