# Generated by Django 3.0.7 on 2020-06-26 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trimester_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubject',
            name='name',
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Subject'),
        ),
    ]
