# Generated by Django 3.0.7 on 2020-06-26 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200626_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubject',
            name='year',
        ),
    ]
