# Generated by Django 3.0.7 on 2020-06-26 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_studentsubject_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimester',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Student'),
        ),
        migrations.AddField(
            model_name='trimester',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Subject'),
        ),
    ]
