# Generated by Django 3.0.7 on 2020-06-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200626_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trimester',
            old_name='subject',
            new_name='student_subject',
        ),
    ]
