# Generated by Django 3.0.7 on 2020-06-26 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200626_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='trimester',
            name='grade_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Year'),
        ),
    ]
