# Generated by Django 3.0.7 on 2020-06-27 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_studenttask_studenttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttask',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Student'),
        ),
        migrations.AddField(
            model_name='studenttest',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Student'),
        ),
    ]
