# Generated by Django 3.0.7 on 2020-06-29 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_task_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Teacher'),
        ),
    ]
