# Generated by Django 3.0.7 on 2020-06-30 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_test_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttest',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Test'),
        ),
    ]
