# Generated by Django 3.0.7 on 2020-06-30 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_studenttest_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttest',
            name='slug',
        ),
    ]
