# Generated by Django 3.0.7 on 2020-07-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200701_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubject',
            name='tri_1',
        ),
        migrations.RemoveField(
            model_name='studentsubject',
            name='tri_2',
        ),
        migrations.RemoveField(
            model_name='studentsubject',
            name='tri_3',
        ),
    ]
