# Generated by Django 3.0.7 on 2020-07-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200701_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubject',
            name='passed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
