# Generated by Django 3.0.7 on 2020-07-02 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200702_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubject',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Student'),
        ),
    ]
