# Generated by Django 3.0.7 on 2020-07-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20200702_1329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trimester',
        ),
    ]
