# Generated by Django 3.0.7 on 2020-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_task_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttask',
            name='delivered',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
