# Generated by Django 3.0.7 on 2020-07-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20200703_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttask',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
